ProjectX/NewYear/urls.py
from django.urls import path

from  . import views

urlpatterns = [
    path("", views.index, name = "index")
]

ProjectX/ProjectX/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include ("hello.urls")),
    path('NewYear/', include ("NewYear.urls")),
    path('taskmanager/', include("taskmanager.urls"))
]

ProjectX/hello/urls.py
from django.urls import path
from . import views #import views from current directory

#a list of accessible urls on the hello app
urlpatterns = [
    path("", views.index, name = "index"),
    path("brian", views.brian, name = "brian"),
    #str:name renders the name as submitted by the user
    path("<str:name>", views.greet, name = "greet")

]

ProjectX/taskmanager/urls.py
from django.urls import path

from . import views

app_name = "taskmanager"
urlpatterns = [
    path("", views.index, name = "index")
    path("add", views.add, name = "add")
]

ProjectX/NewYear/views.py
#import the datetime module
import datetime

from django.shortcuts import render

# Create your views here.
def index(request):
    #create a variable that accesses datetime now functionality
    now = datetime.datetime.now()
    return render(request, "NewYear/index.html", {
        "NewYear": now.month == 1 and now.day == 1
    })

ProjectX/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

#request argument represents the http request made to access server
def index(request,):
    return render(request, "hello/index.html")

#returns hello brian when the url is visited
def brian(request):
    return HttpResponse("Hello, Brian")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })    

ProjectX/taskmanager/views.py
from django.shortcuts import render

# Create your views here.
tasks = ["me", "myself", "I"]

def index(request):
    return render(request, "taskmanager/index.html", {
        "tasks": tasks
    })

def add(request):
    return render(request, "taskmanager/add.html")

ProjectX/NewYear/templates/NewYear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Is it new year?</title>
        <!-- <link href="{% static 'NewYear/styles.css' %}" rel="stylesheet" -->
    </head>
    <body>
        {% if newyear %}
            <h1> Yes </h1>
        {% else %}
            <h1> No </h1>
        <!----endif is a requirement syntax when if logic is used on html -->     
        {% endif %}
        
    </body>
</html>

ProjectX/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>hello</title>
    </head>
    <body>
        <h1> Hello, {{ name }}</h1>
    </body>
</html>

ProjectX/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>hello!</title>
    </head>
    <body>
        <h1> Hello World!</h1>
    </body>
</html>

ProjectX/taskmanager/templates/taskmanager/add.html
{% extends "taskmanager/layout.html"%}

{% block body %}

    <h1> Add task</h1>
        <form action="{% url 'taskmanager:add '%}" method="post">
            {% csrf_token %}
            <input type="text" name="taskmanager">
            <input type="Submit">
        </form>
        <a href="{% url 'taskmanager:index' %}"> View tasks </a>
{% endblock %}

ProjectX/taskmanager/templates/taskmanager/index.html
{% extends "taskmanager/layout.html"%}

{% block body %}
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'taskmanager:add' %}"> Add task </a>
{% endblock %}

ProjectX/taskmanager/templates/taskmanager/layout.html
<!DOCTYPE html>>
<html>
    <head>
        <title> Task Manager</title>
    </head>
    <body>
        {% block body%}
        {% endblock %}

    </body>
</html>